version: '2'

services:
  serveo:
    image: trumpi/serveo:latest
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: "autossh -M 0 -R 80:nginx:80 -o \"StrictHostKeyChecking no\" serveo.net"
  nginx:
    image: nginx:latest
